namespace PIBFF.Domain.Entities;

/// <summary>
/// Represents a transaction submitted by a third-party partner.
/// This is the canonical domain representation, decoupled from the
/// </summary>
public sealed class PartnerTransaction
{
    public string PartnerId { get; init; } = default!;
    public string TransactionReference { get; init; } = default!;
    public decimal Amount { get; init; }
    public string Currency { get; init; } = default!;
    public DateTimeOffset Timestamp { get; init; }

    /// <summary>
    /// Correlation identifier generated by the BFF for end-to-end tracing
    /// across validation, enrichment and queueing.
    /// </summary>
    public Guid CorrelationId { get; init; } = Guid.NewGuid();
}
